#!/bin/sh
#
# /etc/init.d/rcS
#

echo "Mounting filesystems..."
mount -a
mount -o remount,rw /

echo "Loading script..."
/sbin/m5 readfile > /tmp/script
chmod 755 /tmp/script

if [ -s /tmp/script ]; then
       exec /tmp/script
fi

echo "Script from M5 readfile is empty, starting bash shell..."
/bin/bash
